obj-y += transform.o
obj-y += selinux_policy.o
obj-y += cgroup_hack.o

ccflags-y += -I$(srctree)/drivers/terminalsu/include
ccflags-y += -I$(srctree)/security/selinux -I$(srctree)/security/selinux/include -I$(objtree)/security/selinux
